version: '2.1'
services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:mender-3.2.2-build1
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
        environment:
          SERVER_URL:
          TENANT_TOKEN:

networks:
    mender:
